### ISSUE TITLE
clusterdock on Mac OS

### ISSUE THREAD

**Issue by SandishKumarHN** [clusterdock/clusterdock#46]
**I'm getting an error on Mac OS while running clusterdock start topology_nodebase**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http+docker://localunixsocket/v1.30/containers/ca6e0f29389edd3f1f61ab86585802dff93de39bb78ac1ef498fbefe7a1d3128/start

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/bin/clusterdock", line 11, in <module>
    load_entry_point('clusterdock==1.3.2', 'console_scripts', 'clusterdock')()
  File "/usr/local/lib/python3.6/site-packages/clusterdock/cli.py", line 175, in main
    action.main(args)
  File "/Users/sany/phdata/topology_nodebase/start.py", line 37, in main
    cluster.start(args.network)
  File "/usr/local/lib/python3.6/site-packages/clusterdock/models.py", line 99, in start
    node.start(self.network)
  File "/usr/local/lib/python3.6/site-packages/clusterdock/models.py", line 327, in start
    client.api.start(container=container_id)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 1085, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 502 Server Error: Bad Gateway ("b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'")
```

**Comment by dimaspivak** [comment]
Known issue with the latest version of Docker for Mac. Google about the issues around the /etc/localtime mount and downgrade to an earlier release until they fix it.

**Comment by SandishKumarHN** [comment]
Thanks for reply
**A little hack worked here:**
```
mkdir ~/etc
vi ~/etc/timezone
cat ~/etc/timezone
America/New_York
```

```
'/etc/localtime' to '/Users/sany/etc/timezone'

change in  https://github.com/clusterdock/clusterdock/blob/master/clusterdock/models.py#L218
'binds': { '/Users/sany/etc/timezone':  {'bind': '/etc/localtime', 'mode': 'rw'}}, # special chars not allowed so had to give full path. 
```
